---

#set to latest for uprades
packages_state: present

enabled_services:
    - sshd
    - cronie
    - munin-node
    - cups-browsed


common_packages:
    - alsa-utils
    - cups
    - cronie
    - dnsutils
    - fzf
    - rsync
    - openssh
    - openssl
    - sshpass
    - vim
    - tmux
    - mosh
    - sane
    - acpi
    - munin-node
    - gcc
    - gutenprint
    - make
    - python
    - python-packaging
    - python-dbus-common
    - python-jinja
    - python-pip
    - python-pluggy
    - python-py
    - python-pygments
    - python-pypeg2
    - python-pyqt5
    - python-setuptools
    - python-sip
    - python-tox
    - python-virtualenv
    - python-yaml
    - python
    - python2
    - python2-cairo
    - python2-cffi
    - python2-crypto
    - python2-dbus
    - python2-ecdsa
    - python2-gconf
    - python2-gobject2
    - python2-jinja
    - python2-keybinder2
    - python2-markupsafe
    - python2-notify
    - python2-numpy
    - python2-packaging
    - python2-paramiko
    - python2-pip
    - python2-ply
    - python2-pycparser
    - python2-pygame
    - python2-pygit2
    - python2-setuptools
    - python2-xdg
    - python2-yaml
    - unzip
    - unrar
    - sudo
    - tcpdump
    - wget
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
    - the_silver_searcher

xpackages:
    - xorg-server
    - xterm
    - xfce4-terminal
    - xorg-server-common
    - xorg-server-utils
    - xorg-xinit
    - awesome
    - simple-scan
    - vlc
    - luakit
    - inkscape
    - qt4
    - qt5-base
    - qt5-declarative
    - qt5-location
    - qt5-multimedia
    - qt5-script
    - qt5-sensors
    - qt5-svg
    - qt5-tools
    - qt5-translations
    - qt5-webchannel
    - qt5-webkit
    - qt5-x11extras
    - qt5-xmlpatterns
    - jre8-openjdk-headless
    - xclip
    - xpad
    - zathura
    - zathura-pdf-mupdf
