---

#set to latest for uprades
packages_state: present

enabled_services:
    - sshd
    - cronie
    - munin-node

common_packages:
    - alsa-utils
    - cronie
    - dnsutils
    - fzf
    - rsync
    - openssh
    - openssl
    - sshpass
    - vim
    - tmux
    - mosh
    - acpi
    - munin-node
    - gcc
    - iftop
    - make
    - net-tools
    - python
    - python-packaging
    - python-jinja
    - python-dnspython
    - python-pip
    - python-py
    - python-setuptools
    - python-sip
    - python-tox
    - python-virtualenv
    - python-yaml
    - python2
    - python2-crypto
    - python2-dbus
    - python2-dnspython
    - python2-ecdsa
    - python2-jinja
    - python2-markupsafe
    - python2-packaging
    - python2-pip
    - python2-ply
    - python2-pycparser
    - python2-pygit2
    - python2-setuptools
    - python2-yaml
    - unzip
    - unrar
    - sudo
    - tcpdump
    - wget
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
    - the_silver_searcher
    - tzdata
    - pass
    - wol

xpackages:
    - xorg-server
    - xterm
    - xfce4-terminal
    - xorg-server-common
    - xorg-server-utils
    - xorg-xinit
    - awesome
    - archlinux-xdg-menu
    - slock
    - simple-scan
    - gstreamer
    - gst-plugins-good
    - gst-plugins-bad
    - gst-plugins-ugly
    - vlc
    - pacgraph
    - baobab
    - qutebrowser
    - firefox
    - thunderbird
    - chromium
    - inkscape
    - gimp
    - gtk3-print-backends
    - mirage
    - nemo
    - libreoffice-fresh
    - qt4
    - qt5-base
    - qt5-declarative
    - qt5-location
    - qt5-multimedia
    - qt5-script
    - qt5-sensors
    - qt5-svg
    - powerline
    - powerline-common
    - python-pyqt5
    - python-pypeg2
    - python-pygments
    - python-numpy
    - python2-cairo
    - python2-gconf
    - python2-gobject2
    - python2-cffi
    - python2-paramiko
    - python2-numpy
    - python2-xdg
    - python2-keybinder2
    - flake8
    - qt5-tools
    - qt5-webchannel
    - qt5-webkit
    - jre8-openjdk-headless
    - xclip
    - xpad
    - zathura
    - zathura-pdf-mupdf
    - zathura-djvu
    - zathura-ps
    - texlive-core
    - texlive-fontsextra
    - texlive-langgreek
    - texlive-science
    - texmaker
    - time
