#!/bin/bash
# clone everything necessary for a liveboot

# change country to your needs
mirrorlist=$(wget --tries=3 -T 60 -q -O- "https://www.archlinux.org/mirrorlist/?country=DE&protocol=https&ip_version=4" |sed 's/#Server = https/rsync/'|grep -v '^#'|sed 's/\/$repo\/os\/$arch//')

rand="$[ $RANDOM % 9 ]q;d"
mirror=`echo "$mirrorlist"| sed $rand`
echo mirroring from $mirror
cd /srv/http/pxe/
rsync -av --progress "$mirror/iso/latest/arch" .

systemctl restart dnsmasq
