---

- name: common plays for everyone
  hosts: all
  roles: 
    - { role: packages, tags: ['packages'] }
    - { role: munin-node, tags: ['munin-node'] }
    - sshd
    - autoupdate

- name: firewall
  hosts: all
  roles:
      - firewall
  tags: firewall

- name: munin-server
  hosts: t60
  roles:
      - munin-server
  tags: munin-server 
