---

- name: common plays for everyone
  hosts: all
  roles: 
    - { role: packages, tags: ['packages'] }
    - sshd
    - autoupdate



- name: firewall
  hosts: all
  roles:
      - firewall
  tags: firewall
