---

- name: common plays for everyone
  hosts: all
  roles: 
    - { role: packages, tags: ['packages'] }
    - { role: munin-node, tags: ['munin-node'] }
    - { role: nfsclient, tags: ['nfsclient'] }
    - { role: sshd, tags: ['ssh'] }
    - { role: autoupdate, tags: ['autoupdate'] }
    - { role: firewall, tags: ['firewall'] }

- name: nfsserver
  hosts: t60
  roles:
      - nfsserver
  tags: nfsserver

- name: munin-server
  hosts: t60
  roles:
      - munin-server
  tags: munin-server 

- name: pxe
  hosts: t60
  roles:
      - pxe
  tags: pxe


