---

- name: common plays for everyone
  hosts: all
  roles:
    - { role: packages, tags: ['packages'] }
    - { role: system, tags: ['system'] }
    - { role: munin-node, tags: ['munin-node'] }
    - { role: nfsclient, tags: ['nfsclient'] }
    - { role: sshd, tags: ['ssh'] }
    - { role: autoupdate, tags: ['autoupdate'] }
    - { role: cups-client, tags: ['cups-client', 'cups'] }
    - { role: firewall, tags: ['firewall'] }
  tags: common

- name: nfsserver
  hosts: nfsserver
  roles:
      - nfsserver
      - firewall
  tags: nfsserver

- name: pyload
  hosts: pyload
  roles:
      - pyload
      - firewall
  tags: pyload

- name: munin-server
  hosts: munin-server
  roles:
      - munin-server
      - firewall
  tags: munin-server

- name: pxe
  hosts: pxe
  roles:
      - pxe
      - firewall
  tags: pxe
- name: cups-server
  hosts: cups-server
  roles:
    - cups-server
  tags: 
      - cups-server
      - cups
