#!/bin/bash

# create the dir/file environment for a new ansible role
# add entries in local.yml and the inventory

if [ "$1" = "" ]; then
    echo -e "Usage: makerole <rolename>"
    exit
fi

if [ ! -d roles/$1 ]; then
    echo "creating new role $1 ..." 
else
    echo "role already exists"
    exit
fi

echo -e  "roles/$1/tasks/main.yml\nroles/$1/meta/main.yml"
mkdir -p roles/$1/tasks/
mkdir -p roles/$1/meta/
touch roles/$1/tasks/main.yml
touch roles/$1/meta/main.yml

echo "---" >> roles/$1/tasks/main.yml
echo -e "---\n\ndependencies:\n    - handler" >> roles/$1/meta/main.yml

echo "add entry in local.yml and inventory/hosts"
echo -e "- name: $1\n  hosts: $1\n  roles:\n    - $1\n  tags: $1\n" >> local.yml
echo -e "\n[$1]\n" >> inventory/hosts
