---

- name: install munin-server
  pacman: name=munin state=present

- name: copy config and generate munin hostlist
  template: src=munin.conf dest=/etc/munin/munin.conf

- name: copy munin cronjob
  copy: remote_src=True src=/etc/munin/munin-cron-entry dest=/etc/cron.d/munin

- name: copy vhost config
  template: src=munin-vhost.conf dest=/etc/httpd/conf/extra/munin-vhost.conf
  notify: restart apache

- name: enable vhost
  lineinfile: dest=/etc/httpd/conf/httpd.conf line="Include conf/extra/munin-vhost.conf" 
  notify: restart apache
