---

- name: install common packages
  pacman:
    name:  "{{common_packages}}"
    state: "{{ packages_state }}"

- name: install xpackages
  pacman:
    name: "{{xpackages}}"
    state: "{{ packages_state }}"
  when: "'servers' not in group_names"

- name: enable common service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{enabled_services}}"
