---

- name: install common packages
  pacman: name={{ item }} state={{ UPGRADE|default('present') }}
  with_items: commom_packages

- name: install xpackages
  pacman: name={{ item }} state={{ UPGRADE|default('present') }}
  with_items: commom_packages
  when: "'server' not in group_names"

- name: enable common service
  service: name={{ item }} state=started enabled=yes
  with_items: enabled_services
