---

- name: include secret passwords
  include_vars: secret.yml
  no_log: true

- name: install dnsmasq
  pacman: name=dnsmasq state=present

- name: create tftp dirs
  file:
      path: "{{item}}"
      state: directory
      owner: "{{pxe_chown}}"
      group: "{{pxe_chgrp}}"
      mode: "{{pxe_chmod}}"
  with_items:
      - "{{pxe_tftpdir}}"
      - "{{pxe_tftpdir}}/i686"
      - "{{pxe_tftpdir}}/x86_64"
      - "{{pxe_tftpdir}}/pxelinux.cfg"

# this assumes that the origin
# machine has syslinux installed
- name: copy pxelinux.0 and .c32 files
  copy:
    src: /usr/lib/syslinux/bios/{{item}}
    dest: "{{pxe_tftpdir}}/{{item}}"
  with_items:
      - "pxelinux.0"
      - "gpxelinux.0"
      - "libutil.c32"
      - "ldlinux.c32"
      - "libcom32.c32"
      - "menu.c32"
      - "vesamenu.c32"

- name: copy cronjob to mirror livesystem
  copy:
      src: airootsnapper
      dest: /etc/cron.monthly/
      mode: 0744
      owner: root
      group: root
  notify: restart dnsmasq

- name: download latest livesystem to /srv/http/pxe/arch
  command: /etc/cron.weekly/airootsnapper
  when: download_pxe_files
  notify: restart dnsmasq

- name: put symlinks fo archiso kernel/image
  file:
      src:   "/srv/http/pxe/arch/boot/{{item.src}}"
      dest:  "{{pxe_tftpdir}}/{{item.dest}}"
      owner: "{{pxe_chown}}"
      group: "{{pxe_chgrp}}"
      mode:  "{{pxe_chmod}}"
      state: link
      force: yes
  with_items:
      - { src: "x86_64/archiso.img", dest: "x86_64/archiso.img" }
      - { src: "x86_64/vmlinuz",     dest: "x86_64/vmlinuz" }
      - { src: "i686/archiso.img",   dest: "i686/archiso.img" }
      - { src: "i686/vmlinuz",       dest: "i686/vmlinuz" }
  notify: restart dnsmasq

- name: copy boot menu
  template:
      src: "{{item.src}}"
      dest: "{{pxe_tftpdir}}/{{item.dst}}"
      owner: "{{pxe_chown}}"
      group: "{{pxe_chgrp}}"
      mode: "{{pxe_chmod}}"
  with_items:
      - { src: message, dst: message }
      - { src: default, dst: pxelinux.cfg/default }
  notify: restart dnsmasq

- name: make sure http/pxe exitst
  file: path=/srv/http/pxe/ state=directory

- name: copy autoinstall
  template: src=autoinstall dest=/srv/http/pxe/autoinstall owner=http group=http

- name: copy vhost config
  template: src=pxe-vhost.conf dest=/etc/httpd/conf/pxe-vhost.conf
  notify: restart apache

- name: stop and disable systemd-resolve
  service: name=systemd-resolved state=stopped enabled=no

- name: copy dnsmaq conf
  template: src=dnsmasq.conf dest=/etc/dnsmasq.conf
  notify: restart dnsmasq

- name: start and enable dnsmasq
  service: name=dnsmasq state=started enabled=yes
