---
pxe_tftpdir: "/srv/tftp"
pxe_mirror: "http://mirror.rackspace.com/archlinux/iso/latest/"
pxe_chown: "root"
pxe_chmod: "0755"
pxe_chgrp: "root"
pxe_script: "autoinstall"

partition_plans:
    root:
        sda:
            - { label: arch, type: p, lsector: +50G, number: 1, bootable: true, mkfs: ext4, typehex: 83, mount: / }
            - { label: swap, type: e, lsector: +2G, number: 2, bootable: false, mkfs: swap, typehex: 82, mount: false }
    extrahome:
        sda:
            - { label: arch, type: p, lsector: +50G, number: 1, bootable: true, mkfs: ext4, typehex: 83, mount: / }
            - { label: swap, type: e, lsector: +2G, number: 2, bootable: false, mkfs: swap, typehex: 82, mount: false }
        sdb:
            - { label: home, type: p, lsector: "", number: 1, bootable: false, mkfs: ext4, typehex: 83, mount: /home }
