---

default_source: '{{ internal_subnet }}'
default_dest: '0.0.0.0/0'

rules:
  all:
    ssh:
      protocol: 'tcp'
      port: '22'
      source: '{{ internal_subnet }}'
      dest: '0.0.0.0/0'
    munin:
      protocol: 'tcp'
      port: '4949'
  pyload:
    cnload:
      protocol: 'tcp'
      port: '9996'
    pyload:
      protocol: 'tcp'
      port: '9999'
  pxe:
    tftpd:
      protocol: 'udp'
      port: '69'
    http:
      protocol: 'tcp'
      port: '80'
