---

rules:
  all:
    ssh:
      protocol: 'tcp'
      source: '{{ internal_subnet }}'
      port: '22'
  server:
    cnload:
      protocol: 'tcp'
      source: '{{ internal_subnet }}'
      port: '9996'
    pyload:
      protocol: 'tcp'
      source: '{{ internal_subnet }}'
      port: '9999'
 
