---

rules:
  all:
    ssh:
      protocol: 'tcp'
      source: '{{ internal_subnet }}'
      port: '22'
    munin:
      protocol: 'tcp'
      source: '{{ munin_ip }}'
      port: '4949'
  pyload:
    cnload:
      protocol: 'tcp'
      source: '{{ internal_subnet }}'
      port: '9996'
    pyload:
      protocol: 'tcp'
      source: '{{ internal_subnet }}'
      port: '9999'
 
