---

- name: copy autoupdate
  template: src=autoupdate dest=/etc/cron.daily/autoupdate owner=root group=root mode="u=rwx,g=r,o=r"

- name: copy logrotate
  copy: src=logrotate dest=/etc/logrotate.d/autoupdate owner=root group=root mode="u=rw,g=r,o=r"

- name: clear pkg cache
  cron:
    name: clear pacman cache
    day: "*/3"
    hour: 0
    minute: 0
    job: "pacman -Sc --noconfirm"
