---

- name: restart sshd
  service: name=sshd state=restarted

- name: restart cron
  service: name=cronie state=restarted

- name: restart firewall
  service: name=iptables state=restarted

- name: restart munin-node
  service: name=munin-node state=restarted
