---

- name: restart apache
  service: name=httpd state=restarted

- name: restart sshd
  service: name=sshd state=restarted

- name: restart cron
  service: name=cronie state=restarted

- name: restart firewall
  service: name=iptables state=restarted

- name: restart munin-node
  service: name=munin-node state=restarted

- name: configure munin plugins
  shell: "munin-node-configure --shell | sh"

- name: restart nfs
  service: name=nfs-server state=restarted

- name: reload exports
  command: exportfs -rav

- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart cups
  service: name=org.cups.cupsd state=restarted

- name: restart sane
  service: name=saned.socket state=restarted
