#!/bin/bash

mount -o remount,size=1G /run/archiso/cowspace

if [ "$#" -ne 1 ]
then
    pacman --noconfirm -Sy tmux
    tmux new-session -d -s install
    tmux send-keys -t install "${0} install" 'C-m'
fi

if  [ "$1" == "install" ]
then
    # setup ssh
    pacman --noconfirm -S openssh sshpass parted
    echo root:install | chpasswd
    systemctl start sshd
    
    # parse kernel args for install options
    for param in $(< /proc/cmdline); do 
        [[ "${param%%=*}" = "partition_plan" ]] && plan="${param#*=}"
    done

    # various partition plans
    {% for plan in partition_plans %}
    if [[ "$plan" = {{ plan }} ]]
    then
{% for device in partition_plans[plan] %}
dd if=/dev/zero bs=512 count=512 of=/dev/{{device}}
{% for partition in partition_plans[plan][device] %}
dd if=/dev/zero bs=512 count=512 of=/dev/{{device}}{{partition.number}}
echo "n
{{partition.type}}
{{partition.number}}

{{partition.lsector}}
{% if partition.bootable -%}
a
{% if not loop.first -%}
{{partition.number}}
{% endif -%}
{% endif -%}
t
{% if not loop.first -%}
{{partition.number}}
{% endif -%}
{{partition.typehex}}
w
q
"|fdisk /dev/{{device}}
sleep 2
partprobe /dev/{{device}}
{% if partition.mkfs == "swap" -%}
mkswap -L swap /dev/{{device}}{{partition.number}}
sleep 1
swapon -L swap
{% else -%}
mkfs.{{partition.mkfs}} -L {{partition.label}} /dev/{{device}}{{partition.number}}
sleep 1
{% if partition.mount -%}
mount -t {{partition.mkfs}} /dev/{{device}}{{partition.number}} /mnt{{partition.mount}} 
{% endif %}
{% endif -%}
{% endfor -%}
{% endfor -%}
    fi
    {% endfor -%}
    cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
    grep -E -A 1 '.*Germany.*$' /etc/pacman.d/mirrorlist.bak | sed '/--/d' > /etc/pacman.d/mirrorlist
    pacman -Sy 
    pacstrap /mnt base base-devel git python ansible
    genfstab -Lp /mnt > /mnt/etc/fstab
    function archchroot {
        arch-chroot /mnt /bin/bash -c "$1"
    }
    archchroot "pacman -Sy"
    archchroot "mkinitcpio -p linux"
    archchroot "pacman --noconfirm -S syslinux"
    archchroot "sed -i 's/sda3/sda1/g' /boot/syslinux/syslinux.cfg"
    archchroot "syslinux-install_update -iam"
    archchroot "echo root:{% include "passwd" %}| chpasswd"
    archchroot "mkdir /var/lib/anisble"
    archchroot "/usr/bin/ansible-pull -d /var/lib/ansible -U {{ansible_repo_url}} >> /var/log/install.log"
fi



