---

- name: install nfs
  pacman: name={{item}} state=present
  with_items:
      - nfs-utils
      - libtirpc

- name: enable nfs related daemons
  service: name={{ item }} state=started enabled=yes
  ignore_errors: true
  with_items: 
    - nfs-client.target
    - remote-fs.target
    - rpcbind.service
