---

- name: install cups related packages
  pacman: name={{item}} state=present
  with_items:
      - cups
      - cups-pdf
      - gutenprint
      - sane

- name: copy cupsd.conf
  template: src=cupsd.conf dest=/etc/cups/cupsd.conf
  notify: restart cups

- name: make scanners available to network
  blockinfile:
    dest: /etc/sane.d/saned.conf
    marker: "# {mark} ANSIBLE MANAGED"
    block: |
      localhost
      {{ internal_subnet }}
  notify: restart sane


- name: start/enable cups
  service: name=org.cups.cupsd state=started enabled=yes

- name: start/enable sane
  service: name=saned.socket state=started enabled=yes
