---

- name: start/enable sshd
  service:
    name: sshd.service
    state: started 
    enabled: yes

- name: copy sshd config
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  notify: restart sshd
